name: neo_fund
description: An AI-powered personal finance companion for students.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.5
  
  # UI Components
  google_fonts: ^6.1.0
  lottie: ^2.6.0
  fl_chart: ^0.65.0
  
  # Backend & Storage
  shared_preferences: ^2.5.3
  
  # Authentication
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  
  # Utilities
  intl: ^0.19.0
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.6
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/onboarding1.png
    - assets/onboarding/onboarding2.png
    - assets/onboarding/onboarding3.png
    - assets/icons/app_logo.png
    - assets/animations/
